[package]
name = "mamediff"
version = "0.2.1"
edition = "2021"
authors = ["Takeru Ohta <phjgt308@gmail.com>"]
license = "MIT"
description = "A TUI editor for managing unstaged and staged Git diffs"
homepage = "https://github.com/sile/mamediff"
repository = "https://github.com/sile/mamediff"
readme = "README.md"

[dependencies]
crossterm = "0.28.1"
orfail = "1.1.0"
unicode-width = "0.2.0"

[dev-dependencies]
tempfile = "3.15.0"
